import{a as v,S as M,i as c}from"./assets/vendor-03da8548.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const C="43111947-de2162102976d485b612f31fc",S="https://pixabay.com/api/";async function g(t,e,s){try{return(await v.get(S,{params:{key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const a=document.querySelector(".gallery"),y=new M(".gallery a",{captionsData:"alt",captionDelay:250});y.refresh();function L(t){t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;a.insertAdjacentHTML("beforeend",s)}),y.refresh()}function E(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",a.insertAdjacentElement("afterend",t)}document.querySelector(".scroll-to-top");const q=document.querySelector(".form"),p=document.querySelector(".search-input"),b=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");h();let l="",i=1;const f=15;q.addEventListener("submit",H);async function H(t){if(t.preventDefault(),l=p.value.trim(),i=1,a.innerHTML="",l===""){c.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),d();return}$(),w();try{const e=await g(l,i,f),s=e.totalHits;if(e.hits.length===0){a.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),d();return}else L(e.hits),p.value="",P();f*i>=s&&(d(),E())}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{h()}}u.addEventListener("click",async()=>{try{u&&(i+=1);const t=await g(l,i,f),e=t.totalHits;L(t.hits),w(),f*i>=e&&(d(),E());const s=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),c.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{h()}});function w(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function P(){u.style.display="block"}function d(){u.style.display="none"}function $(){const t=document.querySelector(".end-message");t&&t.remove()}
//# sourceMappingURL=commonHelpers.js.map
